#!/usr/bin/env groovy

node {
    stage('Build') {
        sh "echo ${GERRIT_REFSPEC}"
        sh "echo ${PWD}"
        dir('spack')
        sh ". share/spack/setup-env.sh"

        sh "echo \$5(which spack)"
    }
}
